Resources:
    ECRRepository:
        Type: "AWS::ECR::Repository"
        Properties:
            RepositoryName: "projeto_humhub"
            LifecyclePolicy: 
                RegistryId: "891856990808"

