
# TODO EFS
    EFSFileSystem2:
        Type: "AWS::EFS::FileSystem"
        Properties:
            PerformanceMode: "generalPurpose"
            Encrypted: true
            ThroughputMode: "elastic"
            FileSystemTags: 
              - 
                Key: "Name"
                Value: "efs-humhub"

    EFSMountTarget3:
        Type: "AWS::EFS::MountTarget"
        Properties:
            FileSystemId: !Ref EFSFileSystem2
            SecurityGroups: 
              - !Ref EC2SecurityGroupEFS
            SubnetId: !Ref EC2Subnet4

    EFSMountTarget4:
        Type: "AWS::EFS::MountTarget"
        Properties:
            FileSystemId: !Ref EFSFileSystem2
            SecurityGroups: 
              - !Ref EC2SecurityGroupEFS
            SubnetId: !Ref EC2Subnet

# TODO RDS
    EC2SecurityGroupRDS:
        Type: "AWS::EC2::SecurityGroup"
        Properties:
            GroupDescription: "Grupo de Seguranca para o RDS do Humhub"
            GroupName: "SG_RDS_humhub"
            Tags: 
              - 
                Key: "projeto"
                Value: "projeto13_grupo06-humhub"
            VpcId: !Ref EC2VPC
            SecurityGroupIngress: 
              - 
                CidrIp: "0.0.0.0/0"
                FromPort: 3306
                IpProtocol: "tcp"
                ToPort: 3306
              - 
                CidrIpv6: "::/0"
                FromPort: 3306
                IpProtocol: "tcp"
                ToPort: 3306
            SecurityGroupEgress: 
              - 
                CidrIp: "0.0.0.0/0"
                IpProtocol: "-1"
              - 
                CidrIpv6: "::/0"
                IpProtocol: "-1"

    RDSDBInstance:
        Type: "AWS::RDS::DBInstance"
        Properties:
            DBInstanceIdentifier: "database-tecnoct"
            AllocatedStorage: 50
            DBInstanceClass: "db.t3.micro"
            Engine: "mysql"
            MasterUsername: "root"
            MasterUserPassword: "humhub2023"
            DBName: "db_humhub"
            PreferredBackupWindow: "07:09-07:39"
            BackupRetentionPeriod: 0
            AvailabilityZone: !GetAtt EC2Subnet.AvailabilityZone
            PreferredMaintenanceWindow: "sat:04:21-sat:04:51"
            MultiAZ: false
            EngineVersion: "8.0.33"
            AutoMinorVersionUpgrade: true
            LicenseModel: "general-public-license"
            PubliclyAccessible: true
            StorageType: "gp3"
            Port: 3306
            StorageEncrypted: true
            CopyTagsToSnapshot: true
            MonitoringInterval: 0
            EnableIAMDatabaseAuthentication: false
            EnablePerformanceInsights: false
            DeletionProtection: false
            DBSubnetGroupName: !Sub "default-${EC2VPC}"
            VPCSecurityGroups: 
              - !Ref EC2SecurityGroupRDS
            MaxAllocatedStorage: 1000
            DBParameterGroupName: "default.mysql8.0"
            OptionGroupName: "default:mysql-8-0"
            CACertificateIdentifier: "rds-ca-2019"

    RDSDBSubnetGroup:
        Type: "AWS::RDS::DBSubnetGroup"
        Properties:
            DBSubnetGroupDescription: "Created from the RDS Management Console"
            DBSubnetGroupName: !Sub "default-${EC2VPC}"
            SubnetIds: 
              - !Ref EC2Subnet
              - !Ref EC2Subnet2
              - !Ref EC2Subnet3
              - !Ref EC2Subnet4
